version: "1" # 버전 지정

services: # 컨테이너 설정
  master:
    image: mysql:5.7 # 컨테이너에서 사용하는 base image 지정
    restart: always # 컨테이너 다운 시 재시작하라는 명령어
    environment: # 컨테이너 안의 환경변수 설정
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    ports: # -p 옵션과 동일
      - "3307:3306"
    networks:
      my-network:
        ipv4_address: 172.35.1.4

  slave1:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    ports:
      - "3308:3306"
    networks:
      my-network:
        ipv4_address: 172.35.1.3

  slave2:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    ports:
      - "3309:3306"
    networks:
      my-network:
        ipv4_address: 172.35.1.2

networks:
  my-network:
    name: my-network
    ipam:
      driver: default
      config:
        - subnet: 172.35.0.0/20
          gateway: 172.35.0.1